- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS


# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/world/empty/model/my_robot_bringup/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS


# - ros_topic_name: "/tf"
#   gz_topic_name: "/model/my_robot_bringup/tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS



# - ros_topic_name: "/fl_base_shoulder/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/fl_base_shoulder/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/fl_shoulder_femur/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/fl_shoulder_femur/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/fl_femur_tibia/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/fl_femur_tibia/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ


# - ros_topic_name: "/fr_base_shoulder/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/fr_base_shoulder/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/fr_shoulder_femur/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/fr_shoulder_femur/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/fr_femur_tibia/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/fr_femur_tibia/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ


# - ros_topic_name: "/bl_base_shoulder/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/bl_base_shoulder/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/bl_shoulder_femur/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/bl_shoulder_femur/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/bl_femur_tibia/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/bl_femur_tibia/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ


# - ros_topic_name: "/br_base_shoulder/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/br_base_shoulder/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/br_shoulder_femur/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/br_shoulder_femur/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/br_femur_tibia/cmd_pos"
#   gz_topic_name: "/model/my_robot_bringup/joint/br_femur_tibia/0/cmd_pos"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ