controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_position_controller:
      type: position_controllers/JointGroupPositionController


joint_position_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - fl_base_shoulder
      - fl_shoulder_femur
      - fl_femur_tibia
      - fr_base_shoulder
      - fr_shoulder_femur
      - fr_femur_tibia
      - bl_base_shoulder
      - bl_shoulder_femur
      - bl_femur_tibia
      - br_base_shoulder
      - br_shoulder_femur
      - br_femur_tibia
    
    interface_name: position
    #ros2 topic pub --once /joint_position_controller/commands std_msgs/msg/Float64MultiArray "{data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}"